spring:
  main:
    web-application-type: reactive
  config:
    import: classpath:business.yml

server:
  port: 8080

url:
  base-url: http://localhost:8080
  naverworks: https://www.worksapis.com/v1.0