spring:
  main:
    web-application-type: reactive

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.cloud.gateway: DEBUG
    kr.co.danal.naverworks.api.gateway: DEBUG

url:
  base-url: http://localhost:8080
  naverworks: https://www.worksapis.com/v1.0

bot:
  privatekey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6TbAZanbXk3e7
    AMZXk/c7ZYmS7gAEyV3JFtbUFM1JghPM7+6GCDT5l127zrZGfkwZ1dZdqZiN8L8Q
    sP3inzkyzZBtwceI493Q6nnWaweL3wRl4kMZqJ6gvS4hpsORnTkKNRXaysXI011u
    yL6c5/gH5qyHodeDuN5ndnwEkaF265NYfFZe6H+4p1Erfci+eSVwRT4Xp6FT5f+0
    bbDUfY8HuozH4h2qbyFlXOwFiGyGIVLSOe4QGFetoqtwqPKg0ovm1m+gBtWWuZmS
    Bvq44Uv/wkynNgGl+NdGXBfLzWWzFHjbWsBJ0ZN0k/sdpxac+sEmaTZOFHJaev8/
    Q5O4EdJrAgMBAAECggEAFii1YGCEYCG/JPPzo2kLB/qMwXgjcm5NBGT+Cl2rCSo6
    lq6XDUQeoO07DeKJVZsiDBSeGafZaFCROTgECpdrozpGCnf49rQ7puSsty8lx6Iw
    ELo3xu6CZ5X4zbHbIw+zQB6OSebCXZ+eRlYELf99RdtO/Bbo3lb3xRCXsadssAsi
    gCNlKcXpkbQskmRNVXMT8C6aUStQp84BGkd/eEXSh1E4TcRozoQe1MvCquyIDVgK
    gqBNeU6AVw4gzriTOkbfbyEYcrSQGPtpfvXJbl08Cb73cEy4zl5CuwXpKimQuUUU
    efjKca0eK49bjtM9peahC/Zxp2RYfyJfNSppVcw8iQKBgQD+F0Xf/PTOPFcm0kyB
    VGuhoV0/0x9Ms+Uv65nowv+ZicGg5M9YVGik48Ct1FD283uiQehrzQkGpdJdUkrc
    fD+AlvJt5PmYFTi2onTFzr8xq7uBvRhrUbr/U6SJ27BmWlKHV65U5aV3JYcNp5jQ
    Av8/BxffKjUHkVsHJgqmefUMPwKBgQC7tAfAd7kw9NE5RdHy68vaExFKob+9c4v/
    TAJ1JqHk5wpwPSrKweEiU3s40QzMgjDHTRCkucAECBgJH5paOnGOJx3rmhx8NyIn
    26jrkwxhoL6I/iTGqzyXopABzPLl9zEWbTN7sr5kV0bB+RE/szqACKx9Awf66VjG
    GJP63XDe1QKBgFpS6Zr7MAcUOiLpxRqAaRZ251Al+81nccR8KyUsFHJ/Ht7UF8Ud
    lGlxMPBaNkHjQgLnDPktVNURI1vbQhNo86YBgsKAEB35BUUfMQWUPjEpDCnNj52u
    2xuiny4Gc4me+BF2oNk7HXviUkUPW+ot9pBwNBM3zMwY5tP+uPB/EBY/AoGBAI2w
    XXWlKm9RLqp8EPq9kfkBEblzleht040YlHZYfjbrTM7i7W12ovqlZ8vAyleKI0Ye
    32RpLxAcCADDEWHw4g07a/OQNtZxS+AoiT+ileMQUyPYLGynkCqqtOgXDHgZe72B
    Gy7SA7R8yVXdLG8YXR2O7p3Dbv+xq6iFnxbsl6otAoGAbwyJRS7IvooZaXWFBpi+
    BQX+snnsWZPQmtvhyFGnxWnDPtr7QCYKi65dt5bMG48d1+mHMiwt8GtcRiSO7pek
    N3gN7ribQH9nZKObeHh9P6JkveLp2sGHgeENlVpzym+BjjyUSzbUACMutibYbkwc
    UoxPfe2dncPS90PFgZTyCRs=
    -----END PRIVATE KEY-----
  client-id: 7eWUj0HqbhSzhkPR8URA
  client-secret: KHsyhhkIzY
  service-account: qdhxo.serviceaccount@danal2.by-works.com
  scope: audit audit.read board board.read bot bot.read calendar calendar.read contact contact.read directory directory.read group group.read orgunit orgunit.read user user.read
  ids:
    jira: 7996225
    confluence: 7996226
    github: 7996227
    channel: 8076239

channels:
  file:
    path: src/main/resources/channels.json
  message:
    start: |
      안녕하세요 채널관리봇입니다 :)
      수행할 명령어를 입력해주세요.
      
      1. 등록된 채널 조회
       : get
      2. 채널ID 등록하기
       : add/{채널명}/{채널ID}
      3. 등록된 채널ID 수정하기
       : update/{채널명}/{채널ID}
      4. 등록된 채널ID 삭제하기
       : delete/{채널명}
      5. 가이드 보기
       : guide
    guide: |
      1. 등록할 메시지 채널을 클릭하세요. 
      2. "더보기" -> "채널ID" -> "채널ID 복사"를 클릭하세요.
      3. 메시지 "새로 만들기" -> "사내 구성원과 대화" -> "Bot" -> "채널관리봇"을 선택하세요.
      4. "시작하기"를 클릭하고 명령어를 입력하세요. 
          ex. add/{채널명}/{채널ID}
      5. 정상적으로 채널이 등록되면, "success" 메시지를 회신해요.
      6. "http://localhost:8080/message/{platform}/channels/{채널명}"으로 메시지를 발송하세요.
          * 메시지 형식 참고
          {
              "content": {
                  "type": "text",
                  "text": "테스트트트트기술전략"
              }
          }